In [3]:
import numpy as np #numpy를 부를 건데 numpy 를 np로 부를거야.. 이런 의미

In [33]:
a = np.array([1,2,3])

In [34]:
arr = np.array([2,1,5,3,7,4,6,8])

In [35]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [37]:
arr = np.sort(arr)

In [39]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [42]:
np.concatenate((a,b)) #일직선으로 묶임

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [45]:
y

array([[5, 6]])

In [47]:
x

array([[1, 2],
       [3, 4]])

In [48]:
y

array([[5, 6]])

In [49]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
a = np.array([[[0, 1, 2, 3],
                [4, 5, 6, 7]],

                [[0, 1, 2, 3],
                [4, 5, 6, 7]],

                [[0 ,1 ,2, 3],
                [4, 5, 6, 7]]])

In [66]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [67]:
a.ndim

3

In [68]:
a.shape

(3, 2, 4)

In [69]:
a = np.arange(6)

In [70]:
a

array([0, 1, 2, 3, 4, 5])

In [71]:
b = a.reshape(3, 2)

In [74]:
print (b)

[[0 1]
 [2 3]
 [4 5]]


In [82]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [83]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [84]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [85]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [86]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [87]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [88]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [89]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [90]:
data = np.array([1, 2, 3])
data[1]

2

In [91]:
data [0:2]

array([1, 2])

In [92]:
data[1:]

array([2, 3])

In [96]:
data[-2:]

array([2, 3])

In [97]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [98]:
a[a<5]

array([1, 2, 3, 4])

In [104]:
b=(a>=5)

In [105]:
b

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [107]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [109]:
c = a[(a > 2) & (a < 11)]

In [110]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [112]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [113]:
b = np.nonzero(a < 5)

In [114]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [115]:
print (b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [117]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print (coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [118]:
a[b]

array([1, 2, 3, 4])

In [119]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [120]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [122]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [123]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [124]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [125]:
x = np.arange(1, 25).reshape(2, 12)

In [126]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [127]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [128]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [129]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [130]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [131]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [132]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
b2 = a.copy()

In [134]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [135]:
data-ones

array([0, 1])

In [136]:
data*data

array([1, 4])

In [137]:
data/data

array([1., 1.])

In [138]:
a = np.array([1, 2, 3, 4])

In [139]:
a.sum()

10

In [140]:
b = np.array([[1, 1], [2, 2]])

In [141]:
b.sum(axis=0)

array([3, 3])

In [142]:
b.sum(axis=1)

array([2, 4])

In [143]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [144]:
data.max()

2.0

In [145]:
data.min()

1.0

In [146]:
data.sum()

3.0

In [147]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [148]:
a.sum()

4.8595784

In [149]:
a.min()

0.05093587

In [150]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [151]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [152]:
data[0, 1]

2

In [153]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [154]:
data[0:2, 0]

array([1, 3])

In [155]:
data.max()

6

In [156]:
data.min()

1

In [157]:
data.sum()

21

In [158]:
ata = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [159]:
data.max(axis=0)

array([5, 6])

In [160]:
data.max(axis=1)

array([2, 4, 6])

In [161]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [162]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [163]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [164]:
np.ones(3)

array([1., 1., 1.])

In [165]:
np.zeros(3)

array([0., 0., 0.])

In [166]:
rng = np.random.default_rng()

In [167]:
rng.random(3)

array([0.08628931, 0.61012827, 0.03975157])

In [168]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [169]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [170]:
rng.random((3, 2))

array([[0.81760253, 0.98581063],
       [0.91522199, 0.41401609],
       [0.30859291, 0.25985919]])

In [171]:
rng.integers(5, size=(2, 4))

array([[3, 1, 2, 3],
       [0, 1, 4, 4]], dtype=int64)

In [172]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [173]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [174]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [175]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [176]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [177]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [178]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [179]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [180]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [181]:
print(indices)

[0 1 2]


In [182]:
print(occurrence_count)

[2 1 1]


In [183]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [185]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [187]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [188]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [189]:
reversed_arr = np.flip(arr)

In [190]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [191]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [192]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [193]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [194]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [195]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [196]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [197]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [198]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [200]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [201]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [202]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


In [203]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [204]:
a = np.array([1, 2, 3, 4, 5, 6])

In [205]:
a

array([1, 2, 3, 4, 5, 6])

In [209]:
def double(a):
    return a*2

In [210]:
double(2)

4

In [211]:
double(a)

array([ 2,  4,  6,  8, 10, 12])